services:
  proxy:
    image: nginx:latest
    ports:      
      - "80:80"
      - "443:443"
    volumes:
      - ./ProxyServers/Nginx/nginx.conf:/etc/nginx/nginx.conf
    secrets:
      - nginx.cert
      - nginx.key
      - dhparam.pem
    stdin_open: true
    tty: true  

  pocorchestrationngwebui:
    image: ${DOCKER_REGISTRY-}pocorchestrationngwebui
    build:
      context: ./ngwebui
      dockerfile: dockerfile
    volumes:      
      - "./ngwebui:/app"
      - alpine-node-modules:/app/node_modules

  poc.orchestration.api:
    image: ${DOCKER_REGISTRY-}pocorchestrationapi
    build:
      context: .
      dockerfile: PoC.Orchestration.Api/Dockerfile

secrets:
  nginx.cert: 
    file: ./ProxyServers/Certificates/selfsigned.crt
  nginx.key: 
    file: ./ProxyServers/Certificates/selfsigned.key
  dhparam.pem:
    file: ./ProxyServers/Certificates/dhparam.pem

volumes:
  alpine-node-modules: