FROM node:lts-alpine

# set working directory
WORKDIR /app

COPY ./package*.json /app

# install and cache app dependencies
RUN npm i
RUN npm install -g @angular/cli

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add app
COPY . /app

EXPOSE 4200

# start app
CMD ng serve --host 0.0.0.0 --ssl --poll 100
